// Publish independent source branches at stable URLs; never merge itineraries.
import { execFileSync } from 'node:child_process';
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const source = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const output = resolve(process.argv[2] || resolve(source, '../travel-pages'));
const git = (args, cwd = source) => execFileSync('git', args, { cwd, encoding: 'utf8' }).trim();
const read = (ref, file) => execFileSync('git', ['show', `${ref}:${file}`], { cwd: source });
const branch = 'guangdong-national-day-2026';
if (output === source) throw new Error('Publication must use a separate worktree.');
if (git(['branch', '--show-current']) !== branch) throw new Error('Run from the Guangdong source branch.');
if (git(['status', '--porcelain'])) throw new Error('Commit source changes before building.');
if (git(['rev-parse', 'HEAD']) !== git(['rev-parse', `origin/${branch}`])) throw new Error('Push the Guangdong source branch before building.');
if (git(['branch', '--show-current'], output) !== 'gh-pages') throw new Error('Output must be a gh-pages worktree.');
if (git(['status', '--porcelain'], output)) throw new Error('Publication worktree has uncommitted changes.');
if (git(['rev-parse', 'HEAD'], output) !== git(['rev-parse', 'origin/gh-pages'])) throw new Error('Update the publication worktree to origin/gh-pages before building.');

const entries = [
  { id: 'qinggan', branch: 'main', path: '/' },
  { id: 'guangxi', branch: 'guangxi-national-day-2026', path: '/guangxi/' },
  { id: 'guangdong', branch, path: '/guangdong/' },
];
const publication = {}, files = [];
for (const entry of entries) {
  const commit = git(['rev-parse', `origin/${entry.branch}`]);
  publication[entry.id] = { branch: entry.branch, commit, path: entry.path };
  const prefix = entry.path.slice(1);
  files.push([`${prefix}index.html`, commit, 'index.html']);
  if (entry.id === 'qinggan') continue;
  const doc = `docs/${entry.id}-2026-national-day.md`, sql = `supabase/${entry.id}.sql`;
  files.push([prefix + doc, commit, doc], [prefix + sql, commit, sql]);
  const assets = git(['ls-tree', '-r', '--name-only', commit, '--', 'assets/vendor/leaflet']).split(/\r?\n/).filter(Boolean);
  for (const file of assets) files.push([prefix + file, commit, file]);
}
// Resolve and read all sources before changing any publication files.
const content = files.map(([destination, ref, file]) => [resolve(output, destination), read(ref, file)]);
for (const [path, bytes] of content) {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, bytes);
}
writeFileSync(resolve(output, '.nojekyll'), '');
writeFileSync(resolve(output, '.gitattributes'), 'guangxi/assets/vendor/leaflet/** -text\nguangdong/assets/vendor/leaflet/** -text\n');
writeFileSync(resolve(output, 'publication.json'), JSON.stringify(publication, null, 2) + '\n');
writeFileSync(resolve(output, 'README.md'), '# Travel published pages\n\nGenerated by scripts/build-pages.mjs on guangdong-national-day-2026.\n\n' + entries.map(e => `- ${e.id}: https://jinnafu.github.io/travel${e.path} (${e.branch} @ ${publication[e.id].commit})`).join('\n') + '\n\nEdit the independent source branches, then rebuild from the Guangdong branch and publish gh-pages.\n');
console.log(JSON.stringify({ output, publication, files: files.map(x => x[0]) }, null, 2));
