// Build two independent itineraries into the gh-pages publication worktree.
// Run from guangxi-national-day-2026 after committing and pushing source changes.
import { execFileSync } from 'node:child_process';
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const source = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const output = resolve(process.argv[2] || resolve(source, '../travel-pages'));
const git = (args, cwd = source) => execFileSync('git', args, { cwd, encoding: 'utf8' }).trim();
const read = (ref, file) => execFileSync('git', ['show', `${ref}:${file}`], { cwd: source });

if (git(['branch', '--show-current']) !== 'guangxi-national-day-2026') {
  throw new Error('Run from the Guangxi source branch.');
}
if (git(['status', '--porcelain'])) throw new Error('Commit source changes before building.');
if (git(['rev-parse', 'HEAD']) !== git(['rev-parse', 'origin/guangxi-national-day-2026'])) {
  throw new Error('Push the Guangxi source branch before building.');
}
if (git(['branch', '--show-current'], output) !== 'gh-pages') {
  throw new Error('Output must be a separate gh-pages worktree.');
}
if (git(['status', '--porcelain'], output)) throw new Error('Publication worktree has uncommitted changes.');

const qinggan = git(['rev-parse', 'origin/main']);
const guangxi = git(['rev-parse', 'HEAD']);
const files = [
  ['index.html', qinggan, 'index.html'],
  ['guangxi/index.html', guangxi, 'index.html'],
  ['guangxi/docs/guangxi-2026-national-day.md', guangxi, 'docs/guangxi-2026-national-day.md'],
  ['guangxi/supabase/guangxi.sql', guangxi, 'supabase/guangxi.sql'],
];
const assets = git(['ls-tree', '-r', '--name-only', guangxi, '--', 'assets/vendor/leaflet']).split(/\r?\n/).filter(Boolean);
for (const file of assets) files.push([`guangxi/${file}`, guangxi, file]);
for (const [destination, ref, file] of files) {
  const path = resolve(output, destination);
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, read(ref, file));
}
writeFileSync(resolve(output, '.nojekyll'), '');
writeFileSync(resolve(output, 'publication.json'), JSON.stringify({
  qinggan: { branch: 'main', commit: qinggan, path: '/' },
  guangxi: { branch: 'guangxi-national-day-2026', commit: guangxi, path: '/guangxi/' },
}, null, 2) + '\n');
writeFileSync(resolve(output, 'README.md'), `# Travel published pages\n\nThis branch contains publication output, generated by scripts/build-pages.mjs on the Guangxi source branch.\n\n- Qinggan: https://jinnafu.github.io/travel/ (main @ ${qinggan})\n- Guangxi: https://jinnafu.github.io/travel/guangxi/ (guangxi-national-day-2026 @ ${guangxi})\n\nEdit the source branches, then rebuild and push this branch. Do not edit publication output directly.\n`);
console.log(JSON.stringify({ output, qinggan, guangxi, files: files.map(x => x[0]) }, null, 2));
